### ISSUE TITLE
User is not authorized to view runs and manage things in Azure ML Studio after running `teraform apply`

### ISSUE THREAD

**Issue by fschlz** [microsoft/azureml-terraform-examples#4]
I've had this issue in this configuration and in others, too. Also on multiple subscriptions.
I get the following error after just running the Terraform script.
<img width="370" alt="image" src="https://user-images.githubusercontent.com/22344801/211409868-26675d34-4b52-47de-8b06-41c8b839d4ab.png">

Notebook folder structure is also missing that is usually there when creating the resouce manually.
<img width="474" alt="image" src="https://user-images.githubusercontent.com/22344801/211410888-21661113-b485-4846-b5ea-ff398336e170.png">

Plus, folder creation is also fruitless.
<img width="474" alt="image" src="https://user-images.githubusercontent.com/22344801/211410962-8e692a29-6caf-410a-878b-8c59cfb28fac.png">

In the end, all the resources get created, but apparently there are some permission that are not being set? Or the API is broken?
The provisioning script doesn't throw any errors and the link behind "You are not authorized to access this resource." doesn't lead anywhere, so I'll keep searching. But maybe someone here knows something.

**Comment by MathKlim** [comment]
I had the same problem, I had to add `public_network_access_enabled = true` in my workspace configuration to make it work.

**Comment by fschlz** [comment]
> I had the same problem, I had to add `public_network_access_enabled = true` in my workspace configuration to make it work.

Right, I did the same thing. Sorry for not updating.
